version: '2'
services:
  enginservitude-app:
    image: enginservitude
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://enginservitude-postgresql:5432/enginServitude
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://enginservitude-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://enginservitude-elasticsearch:9200
    ports:
      - 8080:8080
  enginservitude-postgresql:
    extends:
      file: postgresql.yml
      service: enginservitude-postgresql
  enginservitude-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: enginservitude-elasticsearch
